# Generated by Django 5.2.4 on 2025-08-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_date_read_book_description_book_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
